/*
 * Generated by tools/pixel-art/build.mjs. Do not edit by hand.
 *
 * The artwork's source is the drawing code in tools/pixel-art; this module is only the index of
 * what that produced. Every sprite shares one art-pixel grid, one palette and one light
 * direction, and every one of them is meant to be scaled by whole numbers.
 */

export interface PixelImage {
  readonly src: string;
  readonly w: number;
  readonly h: number;
}

/** Cached under /art. Scale these by integers and render them with image-rendering: pixelated. */
export const ART: Record<string, PixelImage> = {
  streetWide: {
    src: "/art/street-wide.png",
    w: 320,
    h: 144,
  },
  streetTall: {
    src: "/art/street-tall.png",
    w: 144,
    h: 250,
  },
  busNear: {
    src: "/art/bus-near.png",
    w: 100,
    h: 32,
  },
  busNearB: {
    src: "/art/bus-near-b.png",
    w: 100,
    h: 32,
  },
  busFar: {
    src: "/art/bus-far.png",
    w: 64,
    h: 22,
  },
  busFarB: {
    src: "/art/bus-far-b.png",
    w: 64,
    h: 22,
  },
  busMid: {
    src: "/art/bus-mid.png",
    w: 64,
    h: 22,
  },
  busMidB: {
    src: "/art/bus-mid-b.png",
    w: 64,
    h: 22,
  },
  busFront: {
    src: "/art/bus-front.png",
    w: 40,
    h: 34,
  },
  shelter: {
    src: "/art/shelter.png",
    w: 60,
    h: 48,
  },
  stopFlag: {
    src: "/art/stop-flag.png",
    w: 18,
    h: 52,
  },
  tree: {
    src: "/art/tree.png",
    w: 34,
    h: 46,
  },
  personWaiting: {
    src: "/art/person-waiting.png",
    w: 11,
    h: 21,
  },
  cloud: {
    src: "/art/cloud.png",
    w: 46,
    h: 14,
  },
  bin: {
    src: "/art/bin.png",
    w: 12,
    h: 18,
  },
  edgeWide: {
    src: "/art/street-wide-edge.png",
    w: 32,
    h: 144,
  },
  edgeTall: {
    src: "/art/street-tall-edge.png",
    w: 32,
    h: 250,
  },
};

/** Small enough to inline, and MapLibre needs them without a round trip. */
export const MARKERS: Record<string, PixelImage> = {
  busMarkerRed: {
    src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAALCAYAAABlNU3NAAAAkUlEQVR42mNggAIRQf7/1MQMyAAk8CUsmmwMM/T/zSrsloA4yjoWKPipihZRfHRxGMawwDYwE4xrp68F0yCNxPBhNDJedfAibgtgGF0jLj42C0AYwwKQQmpiDAs2i0nDMTqfGIys59mDK5gWwBQgpwJ0PjaMTw8DOoBJhAV44lZEqR6cmYVSPbzcnP+piWHmAgBfHWWG5uovZQAAAABJRU5ErkJggg==",
    w: 24,
    h: 11,
  },
  busMarkerBlue: {
    src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAALCAYAAABlNU3NAAAAkUlEQVR42mNggAIRQf7/1MQMyAAk4F/7n2wMM/T/zSrsloA4yjoWKFg0/D9RfHRxGMawwDYwE4xrp68F0yCNxPBhNDJedfAibgtgGF0jLj42C0AYwwKQQmpiDAuEbKbBMTqfGIys59mDK5gWwBQgpwJ0PjaMTw8DOoBJhAV44lZEqR6cmYVSPbzcnP+piWHmAgCzum7A8nwcuAAAAABJRU5ErkJggg==",
    w: 24,
    h: 11,
  },
  busMarkerAmber: {
    src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAALCAYAAABlNU3NAAAAj0lEQVR42mNggAIRQf7/1MQMyAAk8P9mFdkYZigyG8USEEdZxwIFf9poQhQfXRyGMSywDcwE49rpa8E0SCMxfBiNjFcdvIjbAhhG14iLj80CEMawAKSQmhjDgq4oBjhG5xODkfU8e3AF0wKYAuRUgM7HhvHpYUAHMImwAE/ciijVgzOzUKqHl5vzPzUxzFwA3/KEKR89AHUAAAAASUVORK5CYII=",
    w: 24,
    h: 11,
  },
  stopMarker: {
    src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAOCAYAAAAbvf3sAAAAUUlEQVR42mNgYGBgEBHk//9URQsvBqlhgAH6aPj+7SNejFUDiL725B0KjSyHVQM2jFMDyU4iSQMxmAEXWDJ7wv+wAE/cCgaxBl5uzv/YMLIaABcO7QeEogPeAAAAAElFTkSuQmCC",
    w: 12,
    h: 14,
  },
};

/** Where the ground and the carriageway sit in each composition, so buses can be driven along it. */
export const SCENE_GEOMETRY = {
  WIDE: {
    w: 320,
    h: 144,
    pavement: 98,
    kerb: 112,
    road: 116,
  },
  TALL: {
    w: 144,
    h: 250,
    pavement: 178,
    kerb: 196,
    road: 200,
  },
} as const;
