import type { Confidence, Coordinate, JourneyPlanRanking } from "@busstops/contracts";
import { haversineMetres } from "@busstops/pipeline-core";
import { walkSeconds, type JourneyGraph, type JourneyStop } from "./graph.js";
import {
  bestArrival,
  reconstructLegs,
  runRaptor,
  type SearchDestination,
  type SearchLeg,
  type SearchOrigin,
} from "./raptor.js";

/**
 * Journey planning (docs/11_JOURNEY_ENGINE.md).
 *
 * Candidate stops are generated by walking time rather than crow-flight distance, itineraries
 * are costed with an explicit reliability penalty that is never double-counted into the ETA,
 * and the returned set is a small diverse Pareto set rather than three near-identical options.
 */

export interface PlanRequest {
  origin: Coordinate;
  destination: Coordinate;
  departAtSeconds: number;
  /** Maximum walk to a boarding stop, in seconds. */
  maxAccessWalkSeconds?: number;
  maxCandidateStops?: number;
  maxRounds?: number;
}

export interface PlannedLeg {
  mode: "walk" | "bus";
  fromStopId: string | null;
  toStopId: string | null;
  fromName: string;
  toName: string;
  routeName?: string;
  headsign?: string;
  departureSeconds: number;
  arrivalSeconds: number;
}

export interface PlannedOption {
  ranking: JourneyPlanRanking;
  legs: PlannedLeg[];
  departureSeconds: number;
  arrivalSeconds: number;
  /** Calibrated arrival interval; the point estimate alone would overstate what we know. */
  arrivalLowSeconds: number;
  arrivalHighSeconds: number;
  totalWalkSeconds: number;
  changeCount: number;
  reliabilityPenaltySeconds: number;
  boardingStopId: string | null;
  confidence: Confidence;
  explanation?: string;
}

export interface PlanResult {
  options: PlannedOption[];
  /** Stops considered for boarding, with the walk to each. */
  candidateStops: Array<{ stop: JourneyStop; walkSeconds: number }>;
  explanation: string | null;
  /**
   * Where a plan with no options stopped.
   *
   * `candidateStops` alone could not answer this: it holds the origin candidates, so a search
   * that failed because nothing was within walking distance of the *destination* looked identical
   * to one that failed in the search itself. Both counts are reported, and whether any round
   * reached a destination at all, which separates "could not board" from "boarded and could not
   * arrive".
   */
  reach: {
    originCandidates: number;
    destinationCandidates: number;
    /** Rounds the search ran, and rounds that produced an itinerary. */
    rounds: number;
    roundsWithOption: number;
  };
}

export const PLANNER_DEFAULTS = {
  maxAccessWalkSeconds: 900,
  maxCandidateStops: 8,
  maxRounds: 3,
  /** Penalty applied per change, reflecting that a missed connection costs more than its wait. */
  transferPenaltySeconds: 180,
  /** Extra penalty when a connection has little slack. */
  fragileTransferPenaltySeconds: 300,
  fragileTransferThresholdSeconds: 240,
} as const;

/** Beyond this, walking the whole way stops being a reasonable suggestion. */
export const MAX_DIRECT_WALK_SECONDS = 45 * 60;

/**
 * A walk-only itinerary. Its arrival is certain in a way no transit option is, so its interval
 * is narrow and its confidence high — the only real uncertainty is the walking pace itself.
 */
function walkOnlyOption(request: PlanRequest, directWalkSeconds: number): PlannedOption {
  const arrivalSeconds = request.departAtSeconds + directWalkSeconds;
  return {
    ranking: "fastest",
    legs: [
      {
        mode: "walk",
        fromStopId: null,
        toStopId: null,
        fromName: "Your starting point",
        toName: "Your destination",
        departureSeconds: request.departAtSeconds,
        arrivalSeconds,
      },
    ],
    departureSeconds: request.departAtSeconds,
    arrivalSeconds,
    arrivalLowSeconds: arrivalSeconds - Math.round(directWalkSeconds * 0.15),
    arrivalHighSeconds: arrivalSeconds + Math.round(directWalkSeconds * 0.25),
    totalWalkSeconds: directWalkSeconds,
    changeCount: 0,
    reliabilityPenaltySeconds: 0,
    boardingStopId: null,
    confidence: {
      level: "high",
      score: 0.9,
      reasons: ["walking only, so nothing depends on a bus running to time"],
    },
    explanation: "Walking the whole way is as quick as waiting for a bus on this journey.",
  };
}

/** Candidate boarding or alighting stops, ranked by walking time and capped. */
export function candidateStops(
  graph: JourneyGraph,
  point: Coordinate,
  maxWalkSeconds: number,
  limit: number,
): Array<{ stop: JourneyStop; walkSeconds: number }> {
  const candidates: Array<{ stop: JourneyStop; walkSeconds: number }> = [];

  for (const stop of graph.stops.values()) {
    const seconds = walkSeconds(point, stop.coordinate);
    if (seconds <= maxWalkSeconds) candidates.push({ stop, walkSeconds: seconds });
  }

  candidates.sort((a, b) => a.walkSeconds - b.walkSeconds);

  // If nothing is in range, expand rather than returning no plan at all.
  if (candidates.length === 0) {
    const nearest = [...graph.stops.values()]
      .map((stop) => ({ stop, walkSeconds: walkSeconds(point, stop.coordinate) }))
      .sort((a, b) => a.walkSeconds - b.walkSeconds)
      .slice(0, Math.min(2, graph.stops.size));
    return nearest;
  }

  return candidates.slice(0, limit);
}

export function plan(graph: JourneyGraph, request: PlanRequest): PlanResult {
  const maxAccessWalkSeconds =
    request.maxAccessWalkSeconds ?? PLANNER_DEFAULTS.maxAccessWalkSeconds;
  const maxCandidateStops = request.maxCandidateStops ?? PLANNER_DEFAULTS.maxCandidateStops;
  const maxRounds = request.maxRounds ?? PLANNER_DEFAULTS.maxRounds;

  const origins = candidateStops(graph, request.origin, maxAccessWalkSeconds, maxCandidateStops);
  const destinations = candidateStops(
    graph,
    request.destination,
    maxAccessWalkSeconds,
    maxCandidateStops,
  );

  if (origins.length === 0 || destinations.length === 0) {
    return {
      options: [],
      candidateStops: origins,
      explanation: null,
      reach: {
        originCandidates: origins.length,
        destinationCandidates: destinations.length,
        rounds: 0,
        roundsWithOption: 0,
      },
    };
  }

  const searchOrigins: SearchOrigin[] = origins.map((candidate) => ({
    stopId: candidate.stop.id,
    accessSeconds: candidate.walkSeconds,
  }));
  const searchDestinations: SearchDestination[] = destinations.map((candidate) => ({
    stopId: candidate.stop.id,
    egressSeconds: candidate.walkSeconds,
  }));

  const result = runRaptor(graph, searchOrigins, {
    departAtSeconds: request.departAtSeconds,
    maxRounds,
  });

  // One itinerary per round preserves genuinely different change counts, which is what makes
  // "fewest changes" a distinct answer rather than a relabelled "fastest". Every destination
  // candidate is considered, not only the single earliest: the earliest may be a stop the
  // search reached without boarding anything, which would otherwise discard the whole round.
  const perRound: PlannedOption[] = [];
  for (let round = 0; round < result.labelsByRound.length; round++) {
    const labels = result.labelsByRound[round]!;

    let bestForRound: PlannedOption | null = null;
    for (const destination of searchDestinations) {
      const arrival = bestArrival(labels, [destination]);
      if (!arrival) continue;

      const legs = reconstructLegs(labels, arrival.stopId);
      if (!legs.some((leg) => leg.kind === "board")) continue;

      const option = buildOption(graph, request, origins, legs, arrival, "fastest");
      if (option && (!bestForRound || option.arrivalSeconds < bestForRound.arrivalSeconds)) {
        bestForRound = option;
      }
    }

    if (bestForRound) perRound.push(bestForRound);
  }

  // Walking the whole way is a legitimate answer, and sometimes the right one. Offering it when
  // it beats or nearly matches the transit options is more useful than silently returning
  // nothing, or recommending a bus that gets there later than walking would.
  const directWalk = walkSeconds(request.origin, request.destination);
  const bestTransitArrival =
    perRound.length > 0 ? Math.min(...perRound.map((o) => o.arrivalSeconds)) : null;
  const walkArrival = request.departAtSeconds + directWalk;

  if (
    directWalk <= MAX_DIRECT_WALK_SECONDS &&
    (bestTransitArrival === null || walkArrival <= bestTransitArrival)
  ) {
    perRound.push(walkOnlyOption(request, directWalk));
  }

  if (perRound.length === 0) {
    return {
      options: [],
      candidateStops: origins,
      explanation: null,
      reach: {
        originCandidates: origins.length,
        destinationCandidates: destinations.length,
        rounds: result.labelsByRound.length,
        roundsWithOption: 0,
      },
    };
  }

  const options = rankOptions(perRound);

  // The comparison the explanation needs is "best overall versus nearest feasible", so the
  // nearest stop is evaluated on its own rather than hoping an option boarding there happened
  // to survive ranking.
  const nearest = origins[0];
  const nearestArrivalSeconds =
    nearest === undefined
      ? null
      : arrivalFromSingleStop(graph, request, nearest, searchDestinations, maxRounds);

  const explanation = explainBoardingStop({
    graph,
    origins,
    winner: options[0] ?? null,
    nearestArrivalSeconds,
  });

  return {
    options,
    candidateStops: origins,
    explanation,
    reach: {
      originCandidates: origins.length,
      destinationCandidates: destinations.length,
      rounds: result.labelsByRound.length,
      roundsWithOption: perRound.length,
    },
  };
}

/** Earliest arrival when only one boarding stop is permitted. Used by the stop explanation. */
export function arrivalFromSingleStop(
  graph: JourneyGraph,
  request: PlanRequest,
  origin: { stop: JourneyStop; walkSeconds: number },
  destinations: readonly SearchDestination[],
  maxRounds: number,
): number | null {
  const result = runRaptor(graph, [{ stopId: origin.stop.id, accessSeconds: origin.walkSeconds }], {
    departAtSeconds: request.departAtSeconds,
    maxRounds,
    // The question is "what can I reach boarding here", so walking off to a different stop
    // first would answer a different question and make the comparison meaningless.
    allowInitialFootpaths: false,
  });

  let best: number | null = null;
  for (const destination of destinations) {
    const arrival = bestArrival(result.labelsByRound[result.labelsByRound.length - 1]!, [
      destination,
    ]);
    if (!arrival) continue;
    const legs = reconstructLegs(
      result.labelsByRound[result.labelsByRound.length - 1]!,
      arrival.stopId,
    );
    // Only count it if a bus was actually boarded from this stop.
    if (!legs.some((leg) => leg.kind === "board")) continue;
    if (best === null || arrival.arrivalSeconds < best) best = arrival.arrivalSeconds;
  }
  return best;
}

function buildOption(
  graph: JourneyGraph,
  request: PlanRequest,
  origins: ReadonlyArray<{ stop: JourneyStop; walkSeconds: number }>,
  legs: readonly SearchLeg[],
  arrival: { stopId: string; arrivalSeconds: number; egressSeconds: number },
  ranking: JourneyPlanRanking,
): PlannedOption | null {
  const firstLeg = legs[0];
  if (!firstLeg) return null;

  const boardingStopId = firstLeg.fromStopId;
  const access = origins.find((candidate) => candidate.stop.id === boardingStopId);
  const accessSeconds = access?.walkSeconds ?? 0;

  const planned: PlannedLeg[] = [];
  const originName = "Your starting point";

  if (accessSeconds > 0) {
    planned.push({
      mode: "walk",
      fromStopId: null,
      toStopId: boardingStopId,
      fromName: originName,
      toName: graph.stops.get(boardingStopId)?.name ?? boardingStopId,
      departureSeconds: firstLeg.departureSeconds - accessSeconds,
      arrivalSeconds: firstLeg.departureSeconds,
    });
  }

  let changeCount = 0;
  let walkSecondsTotal = accessSeconds;
  let fragileTransfers = 0;
  let previousArrival: number | null = null;

  for (const leg of legs) {
    const fromName = graph.stops.get(leg.fromStopId)?.name ?? leg.fromStopId;
    const toName = graph.stops.get(leg.toStopId)?.name ?? leg.toStopId;

    if (leg.kind === "transfer") {
      walkSecondsTotal += leg.arrivalSeconds - leg.departureSeconds;
      planned.push({
        mode: "walk",
        fromStopId: leg.fromStopId,
        toStopId: leg.toStopId,
        fromName,
        toName,
        departureSeconds: leg.departureSeconds,
        arrivalSeconds: leg.arrivalSeconds,
      });
      continue;
    }

    if (previousArrival !== null) {
      changeCount += 1;
      const slack = leg.departureSeconds - previousArrival;
      if (slack < PLANNER_DEFAULTS.fragileTransferThresholdSeconds) fragileTransfers += 1;
    }
    previousArrival = leg.arrivalSeconds;

    planned.push({
      mode: "bus",
      fromStopId: leg.fromStopId,
      toStopId: leg.toStopId,
      fromName,
      toName,
      ...(leg.trip ? { routeName: leg.trip.routeName, headsign: leg.trip.headsign } : {}),
      departureSeconds: leg.departureSeconds,
      arrivalSeconds: leg.arrivalSeconds,
    });
  }

  if (arrival.egressSeconds > 0) {
    const lastArrival = legs[legs.length - 1]!.arrivalSeconds;
    walkSecondsTotal += arrival.egressSeconds;
    planned.push({
      mode: "walk",
      fromStopId: arrival.stopId,
      toStopId: null,
      fromName: graph.stops.get(arrival.stopId)?.name ?? arrival.stopId,
      toName: "Your destination",
      departureSeconds: lastArrival,
      arrivalSeconds: lastArrival + arrival.egressSeconds,
    });
  }

  const reliabilityPenaltySeconds =
    changeCount * PLANNER_DEFAULTS.transferPenaltySeconds +
    fragileTransfers * PLANNER_DEFAULTS.fragileTransferPenaltySeconds;

  const departureSeconds = planned[0]?.departureSeconds ?? request.departAtSeconds;
  const confidence = estimateConfidence(changeCount, fragileTransfers, legs);

  // The interval widens with changes and fragility. The penalty above is a *ranking* cost and
  // is deliberately not added to the arrival estimate: doing both would double-count the risk.
  const spread = 120 + changeCount * 120 + fragileTransfers * 120;

  return {
    ranking,
    legs: planned,
    departureSeconds,
    arrivalSeconds: arrival.arrivalSeconds,
    arrivalLowSeconds: arrival.arrivalSeconds - Math.round(spread * 0.4),
    arrivalHighSeconds: arrival.arrivalSeconds + spread,
    totalWalkSeconds: walkSecondsTotal,
    changeCount,
    reliabilityPenaltySeconds,
    boardingStopId,
    confidence,
  };
}

function estimateConfidence(
  changeCount: number,
  fragileTransfers: number,
  legs: readonly SearchLeg[],
): Confidence {
  const reasons: string[] = [];
  let score = 0.85;

  if (changeCount > 0) {
    score -= changeCount * 0.1;
    reasons.push(`${changeCount} ${changeCount === 1 ? "change" : "changes"}`);
  }
  if (fragileTransfers > 0) {
    score -= fragileTransfers * 0.2;
    reasons.push("little time to make a connection");
  }

  const hasLiveData = legs.some((leg) => leg.trip?.delaySeconds !== undefined);
  if (!hasLiveData) {
    score -= 0.15;
    reasons.push("based on the timetable, with no live data for these journeys");
  } else {
    reasons.push("uses live running information");
  }

  score = Math.max(0.05, Math.min(1, score));
  return { level: score >= 0.7 ? "high" : score >= 0.45 ? "medium" : "low", score, reasons };
}

/**
 * Picks the best option for each ranking mode and de-duplicates near-identical results, so the
 * user sees genuinely different choices rather than the same journey three times.
 */
export function rankOptions(options: readonly PlannedOption[]): PlannedOption[] {
  if (options.length === 0) return [];

  const fastest = [...options].sort(
    (a, b) =>
      a.arrivalSeconds +
      a.reliabilityPenaltySeconds -
      (b.arrivalSeconds + b.reliabilityPenaltySeconds),
  )[0]!;

  const earliestArrival = Math.min(...options.map((o) => o.arrivalSeconds));

  // Least walking, subject to not arriving unreasonably later than the best option.
  const leastWalking = [...options]
    .filter((o) => o.arrivalSeconds <= earliestArrival + 900)
    .sort((a, b) => a.totalWalkSeconds - b.totalWalkSeconds)[0];

  const fewestChanges = [...options]
    .filter((o) => o.arrivalSeconds <= earliestArrival + 1200)
    .sort((a, b) => a.changeCount - b.changeCount || a.arrivalSeconds - b.arrivalSeconds)[0];

  const chosen: PlannedOption[] = [{ ...fastest, ranking: "fastest" }];

  if (leastWalking && !isNearDuplicate(leastWalking, fastest)) {
    chosen.push({ ...leastWalking, ranking: "least_walking" });
  }
  if (
    fewestChanges &&
    !isNearDuplicate(fewestChanges, fastest) &&
    !chosen.some((option) => isNearDuplicate(fewestChanges, option))
  ) {
    chosen.push({ ...fewestChanges, ranking: "fewest_changes" });
  }

  return chosen;
}

function isNearDuplicate(a: PlannedOption, b: PlannedOption): boolean {
  return (
    a.boardingStopId === b.boardingStopId &&
    a.changeCount === b.changeCount &&
    Math.abs(a.arrivalSeconds - b.arrivalSeconds) < 60
  );
}

/**
 * The "smart fastest stop" explanation. It only speaks when the difference is larger than the
 * uncertainty in the estimates: claiming a 2-minute advantage from a ±4-minute prediction would
 * be false precision dressed up as advice.
 */
export function explainBoardingStop(input: {
  graph: JourneyGraph;
  origins: ReadonlyArray<{ stop: JourneyStop; walkSeconds: number }>;
  winner: PlannedOption | null;
  /** Earliest arrival achievable boarding at the nearest stop, or null if nothing useful runs. */
  nearestArrivalSeconds: number | null;
}): string | null {
  const { graph, origins, winner, nearestArrivalSeconds } = input;

  if (!winner?.boardingStopId) return null;

  const nearest = origins[0];
  if (!nearest || nearest.stop.id === winner.boardingStopId) return null;

  const winnerStop = graph.stops.get(winner.boardingStopId);
  if (!winnerStop) return null;

  const walkMinutes = Math.round(
    (origins.find((o) => o.stop.id === winner.boardingStopId)?.walkSeconds ?? 0) / 60,
  );

  if (nearestArrivalSeconds === null) {
    return (
      `${winnerStop.name} is a ${walkMinutes} minute walk. ` +
      `We could not find a useful service from ${nearest.stop.name}, the nearest stop.`
    );
  }

  const savingSeconds = nearestArrivalSeconds - winner.arrivalSeconds;
  const uncertainty = winner.arrivalHighSeconds - winner.arrivalSeconds;

  // Claiming an advantage smaller than the uncertainty would be false precision dressed as advice.
  if (savingSeconds <= uncertainty) {
    return (
      `${nearest.stop.name} is closer, and the difference between the two is within the ` +
      `uncertainty of these estimates, so either is a reasonable choice.`
    );
  }

  const savingMinutes = Math.round(savingSeconds / 60);

  return (
    `${winnerStop.name} is a ${walkMinutes} minute walk, but its useful bus is expected sooner; ` +
    `it should get you there about ${savingMinutes} minutes earlier than ${nearest.stop.name}.`
  );
}

/** Straight-line distance, used only for reporting; routing itself uses walking time. */
export function directDistanceMetres(from: Coordinate, to: Coordinate): number {
  return haversineMetres(from, to);
}
