#!/usr/bin/env node
/**
 * Emits `dist/_headers` for Cloudflare Pages with a Content-Security-Policy that names the exact
 * API origin this build talks to.
 *
 * The policy cannot be a static file. The app is served from Pages and calls a Worker on a
 * different origin, so `connect-src` has to name that origin — and the Worker's hostname contains
 * an account-specific subdomain that is only known once it has been deployed. The alternative,
 * `connect-src https:`, would permit the page to talk to any host on the internet, which is most
 * of what a CSP is for.
 *
 *   node scripts/generate-headers.mjs <dist-dir> <api-origin>
 */

import { writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const [, , distDir, apiUrlArg] = process.argv;

if (!distDir || !apiUrlArg) {
  console.error("Usage: node scripts/generate-headers.mjs <dist-dir> <api-origin>");
  process.exit(2);
}

if (!existsSync(distDir)) {
  console.error(`Build directory does not exist: ${distDir}. Build before generating headers.`);
  process.exit(1);
}

let apiOrigin;
try {
  const parsed = new URL(apiUrlArg);
  if (parsed.protocol !== "https:") {
    console.error(`API origin must be https, got ${parsed.protocol}//`);
    process.exit(1);
  }
  // Origin only: a CSP source with a path is ignored by some browsers and misleading in all.
  apiOrigin = parsed.origin;
} catch {
  console.error(`API origin is not a valid URL: ${apiUrlArg}`);
  process.exit(1);
}

/**
 * Mirrors apps/worker/src/security.ts. The Worker hardens its own responses; this covers the
 * pages people actually load, which the Worker never touches.
 */
const csp = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
  "script-src 'self'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  // The one cross-origin permission, and it names a single exact host.
  `connect-src 'self' ${apiOrigin}`,
  "font-src 'self' data:",
  "worker-src 'self' blob:",
  "manifest-src 'self'",
  "upgrade-insecure-requests",
].join("; ");

const headers = `# Generated by scripts/generate-headers.mjs — do not edit by hand.
# connect-src names the exact API origin this build was compiled against:
#   ${apiOrigin}

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: DENY
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Permissions-Policy: geolocation=(self), camera=(), microphone=(), payment=(), usb=(), interest-cohort=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains

# Hashed assets are immutable, so they can be cached hard. The shell must not be, or a deploy
# would not reach anyone still holding the previous index.html.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

/index.html
  Cache-Control: public, max-age=0, must-revalidate

/manifest.webmanifest
  Cache-Control: public, max-age=3600
`;

writeFileSync(join(distDir, "_headers"), headers);
console.log(`Wrote ${join(distDir, "_headers")} allowing connect-src to ${apiOrigin}`);
